name: DevSecOps Pipeline  # Nombre del workflow (puede ser lo que tú quieras)

on:  # ¿Cuándo se ejecuta este pipeline?
  push:  # Cuando haces git push
    branches: [ "main" ]
  pull_request:  # Cuando abres un PR hacia main
    branches: [ "main" ]

jobs:  # Puedes tener uno o varios jobs (bloques de ejecución)

  security-checks:  # Nombre del job
    runs-on: ubuntu-latest  # Máquina donde se ejecuta (máquina virtual en GitHub)

    steps:  # Pasos del job (van en orden)

    - name: Checkout code
      uses: actions/checkout@v4
      # Clona tu repo en la máquina para que se pueda analizar

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install bandit

    - name: Run Bandit (SAST)
      continue-on-error: true
      run: |
        bandit -r app -ll

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
        chmod +x gitleaks
        sudo mv gitleaks /usr/local/bin

    - name: Run Gitleaks (secret scanning)
      continue-on-error: true
      run: |
        gitleaks detect --source=. --no-git --report-format sarif --report-path gitleaks-report.sarif

    - name: Upload Gitleaks report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: gitleaks-report
        path: gitleaks-report.sarif

